remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: Reliance Enwerem (M.A., Doctoral Student)
description: Computational Analyst, Digital Humanities Researcher, Scientific & Technical Communications 