remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: Reliance Enwerem
description: Computational Analyst, Digital Humanities Researcher, Scientifica & Technical Communications 