url: "https://relianceenwerem.github.io/my-portfolio/"
baseurl: "/reliance-sample-portfolio"
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme
title: "Reliance's CV"
description: "Reliance's CV"

